# Configuration for the build_runner package.
targets:
  $default:
    builders:
      # The key here should match the name of the builder in the factory.
      nexus|gpu_shader_builder:
        enabled: true
      # Enable our new binary builder
      nexus|binary_builder:
        enabled: true

builders:
  # A unique key for our GPU builder.
  gpu_shader_builder:
    import: "package:nexus/builder.dart"
    builder_factories: ["gpuShaderBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    build_to: source
    auto_apply: dependents

  # A unique key for our new binary builder.
  binary_builder:
    import: "package:nexus/builder.dart"
    builder_factories: ["binaryBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    # We want this to run on any file that might contain a NetComponent.
    # For simplicity, we'll let it run on all .dart files.
    build_to: source
    auto_apply: dependents
