name: nexus
description: A highly scalable, clean, and data-oriented framework for Flutter, inspired by ECS and powered by BLoC and GetIt.
version: 1.1.0-dev.1
homepage: https://github.com/ShoghShahadat/Nexus 
repository: https://github.com/ShoghShahadat/Nexus 
issue_tracker: https://github.com/ShoghShahadat/Nexus/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4 # For state management components
  get_it: ^7.7.0 # For service location and dependency injection
  meta: ^1.11.0 # For annotations
  collection: ^1.18.0 # Required for EquatableMixin's deep equality checks

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
