name: attractor_example
description: An example project showcasing the Nexus framework's GPU capabilities.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nexus:
    # This now points to the local nexus package we are developing.
    path: ../../
  collection: ^1.18.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  # --- NEW: Add build_runner to the example project as well ---
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
