import 'package:nexus/nexus.dart';
import 'package:collection/collection.dart';

/// A serializable component that holds a "render packet" - a list of declarative
/// drawing commands. This is generated by the CustomPaintingSystem in the logic
/// isolate and consumed by the NexusCanvasBuilder/NexusPainter on the UI thread.
class SceneRenderPacketComponent extends Component with SerializableComponent {
  /// The list of drawing commands. Each map represents one shape to be drawn.
  final List<Map<String, dynamic>> packet;

  SceneRenderPacketComponent(this.packet);

  factory SceneRenderPacketComponent.fromJson(Map<String, dynamic> json) {
    return SceneRenderPacketComponent(
        (json['packet'] as List).cast<Map<String, dynamic>>());
  }

  @override
  Map<String, dynamic> toJson() => {'packet': packet};

  @override
  List<Object?> get props => [
        // Use DeepCollectionEquality for deep comparison of the list of maps.
        const DeepCollectionEquality().hash(packet)
      ];
}
